# The file is just for guess words

FRUITS = (
    "apple",
    "banana",
    "orange",
    "strawberry",
    "mango",
    "watermelon",
    "pineapple",
    "blueberry",
    "raspberry",
    "kiwi",
    "papaya",
    "coconut",
    "peach",
    "lemon",
    "lime",
    "cherry",
    "plum",
    "avocado",
    "guava",
    "passionfruit",
    "pomegranate",
    "fig",
    "date",
    "tangerine",
    "cranberry",
    "blackberry",
    "nectarine",
    "grape",
    "grapefruit",
    "cantaloupe",
)